### PR TITLE
Modernise.

### PR DESCRIPTION
**Pull request by tascord**
### TGM.digital — The modern approach

This is a complete rewrite of the website, using node.js and express made to be hosted on Herouku.
This was purely made for fun, but it turned out particularly well, so feel free to adopt this and remove all the jabs at you.

### Domain
If you'd like me to transfer the domain, [tgm.digital](http://tgm.digital), where the site is currently hosted, you may contact me via [email](mailto:oscar_hill@icloud.com) or through [Discord tickets](https://discord.gg/cayke). Alternatively, if you'd like the site taken down from the domain, you may also contact me through the above channels.

### Final Note
This wasn't made to try and prove I'm better than you or with any malice, purely because I saw your website and thought it would be funny. Please dont overreact to this lol.

Thanks,
Oscar "tascord" Hill.

### CODE REVIEW

**Comment by MatthewTGM** [comment]
Although, that's a template?

**Comment by tascord** [comment]
Hey Matthew,
The code displayed in my repo is my own, not a template.
A lot of the code has been borrowed from my other projects, but still mine.

**Comment by MatthewTGM** [comment]
> Hey Matthew,
> The code displayed in my repo is my own, not a template.
> A lot of the code has been borrowed from my other projects, but still mine.

Although, I've been told that's a template.

**Comment by tascord** [comment]
Hey Matthew,
This comment will document where all of the code and styling comes from.

### Font, Button Styling & Colours
image
[cQ](https://github.com/tascord/cQ) is a forms tool I've been creating over the past few weeks. I thought that the buttons and font would work nicely for this site so decided to take those chunks of scss. The themes.js file, responsible for handing themes also comes from here.

### GitHub Projects
image
[tascord.ai](http://tascord.ai/projects), my website, has the same code and styling for the GitHub repo list as yours does. This website was created multiple months ago, and while the code for it isn't public, I can assure you that all the code from that site used in tgm.digitl, is mine.

### Server.js
The server.js file is the file that looks the closest like boiler plate. However, once again, I can assure you that I wrote this. If you look back throughout my other repositories, you will see similar files using the same conventions as I am here. Also, if you return to  the cQ repo, you will see a very similar index.js file, as server.js is just a modified version of this.

### Final Note
I will once again re-iterate; I am, to the best of my knowlege, the author of 100% of the **code** hosted in the [TGM-Digital](https://github.com/tascord/TGM-Digital) repo. I use some libraries for icons and smooth scrolling, but other than that, everything was hand written. If you do not believe me, I implore you to visit my other website based ventures on github, as they're all written very similarly.

Thanks,
Oscar.

**Comment by MatthewTGM** [comment]
I will think about updating it, I'm moving to a different host anyway. Thank you for the changes you ,made despite my immature behaviour and continuous anger towards your "I'm better" attitude along with many people of the same behaviour in ESS.

**Comment by tascord** [comment]
poggers

**Comment by MatthewTGM** [comment]
After coming to a final conclusion, I will be pulling your changes.

**Pull request closed without merging**
